# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch  
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # issues:
  #   types: [opened, edited, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint --if-present
    - run: npm run test
    - run: npm run build

  print-issue-info:
    runs-on: ubuntu-latest
    steps:
    - name: Print issue event information
      uses: actions/github-script@v6
      with:
        script: |
          console.log(JSON.stringify(context.payload, null, 2));
